package com.jishuli.Moco.PersistenceLayer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COURSE".
 */
public class Course {

    private Long id;
    private Long identifier;
    private String name;
    private long subjectID;

    public Course() {
    }

    public Course(Long id) {
        this.id = id;
    }

    public Course(Long id, Long identifier, String name, long subjectID) {
        this.id = id;
        this.identifier = identifier;
        this.name = name;
        this.subjectID = subjectID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Long identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getSubjectID() {
        return subjectID;
    }

    public void setSubjectID(long subjectID) {
        this.subjectID = subjectID;
    }

}
